Repository automatiza-mg/automatizacoes, pull requests merged in 2025-04, with the labels that each got.

#239 Exclui André da equipe Automatiza
  docs/index.md
Labels: enhancement

#237 228 cria post robo consulta cagec
  docs/projetos/sejusp/consulta_cagec/assets/base_dados_cagec_post.xlsx
  docs/projetos/sejusp/consulta_cagec/consulta_situacao_cagec.md
  docs/projetos/sejusp/index.md
  docs/projetos/sejusp/leitura_fatura_energia_bt.md
  docs/projetos/sejusp/pagamento_ipls.md
  mkdocs.yml
Labels: documentation

#241 Add post de instrucoes do robo-1-secult-upload-di
  docs/projetos/secult/index.md
  docs/projetos/secult/robo_1.md
  mkdocs.yml
Labels: documentation

#244 Ajusta link de acesso a post robo consulta_cagec.
  docs/projetos/sejusp/assets/base_dados_cagec_post.xlsx
  docs/projetos/sejusp/consulta_situacao_cagec.md
  docs/projetos/sejusp/index.md
Labels: bug

#248 Melhora post ipsemg
  docs/projetos/ipsemg/index.md
  docs/projetos/ipsemg/valores_receber_pagar.md
Labels: documentation, enhancement
