Repository automatiza-mg/automatizacoes, pull requests merged in 2025-02, with the labels that each got.

#182 Update requirements.txt
  requirements.txt
Labels: enhancement

#222 216 post robo multas
  docs/robos/consulta_situacao_veiculos/assets/planilha_modelo_multa.csv
  docs/robos/consulta_situacao_veiculos/index.md
Labels: documentation, enhancement

#226 Adiciona etapa de login no site cidadao.mg para criação do robo.
  docs/robos/consulta_situacao_veiculos/index.md
Labels: bug
